databases:
  - name: video_editing_db
    plan: free
    ipAllowList: []
      

services:
  - type: web
    name: video_editing
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: video_editing_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false